#!/bin/bash

if [ -n "${MICRUN_TEST_ENV_SH_LOADED:-}" ]; then
    return 0
fi
MICRUN_TEST_ENV_SH_LOADED=1

export TEST_REMOTE_HOST="${TEST_REMOTE_HOST:-root@192.168.7.2}"
export TEST_REMOTE_PASSWORD="${TEST_REMOTE_PASSWORD:-}"
case "${TEST_REMOTE_HOST}" in
    root@127.0.0.1|127.0.0.1)
        export TEST_REMOTE_PORT="${TEST_REMOTE_PORT:-${QEMU_SSH_FWD_PORT:-10022}}"
        ;;
    *)
        export TEST_REMOTE_PORT="${TEST_REMOTE_PORT:-}"
        ;;
esac
export TEST_SSH_CONNECT_TIMEOUT="${TEST_SSH_CONNECT_TIMEOUT:-10}"

export TEST_IMAGE="${TEST_IMAGE:-localhost:5000/mica-uniproton-app:xen-0.1}"
export K3S_SOURCE_IMAGE_REF="${K3S_SOURCE_IMAGE_REF:-docker.io/local/mica-uniproton-app:xen-arm64-0.1}"
export NERDCTL_NETWORK_MODE="${NERDCTL_NETWORK_MODE:-none}"
export IMAGE_PROFILE="${IMAGE_PROFILE:-auto}"
export QEMU_IMAGE_TAR="${QEMU_IMAGE_TAR:-}"
export QEMU_SOURCE_IMAGE_REF="${QEMU_SOURCE_IMAGE_REF:-localhost:5000/mica-uniproton-app:xen-0.1}"

export K3S_MASTER_URL="${K3S_MASTER_URL:-https://192.168.1.100:6443}"
export K3S_MASTER_NODE="${K3S_MASTER_NODE:-$TEST_REMOTE_HOST}"
export K3S_WORKER_NODES="${K3S_WORKER_NODES:-}"
export K3S_KUBECTL_BIN="${K3S_KUBECTL_BIN:-kubectl}"
export K3S_CTR_BIN="${K3S_CTR_BIN:-ctr}"
export K3S_SINGLE_NODE="${K3S_SINGLE_NODE:-false}"
export K3S_HOST_NETWORK="${K3S_HOST_NETWORK:-false}"
export K3S_TOLERATE_NOTREADY="${K3S_TOLERATE_NOTREADY:-false}"
export K3S_CONTAINER_COMMAND="${K3S_CONTAINER_COMMAND:-/micrun-placeholder}"
export K3S_PAUSE_IMAGE="${K3S_PAUSE_IMAGE:-rancher/mirrored-pause:3.6}"
export K3S_PAUSE_IMAGE_CANONICAL="${K3S_PAUSE_IMAGE_CANONICAL:-docker.io/rancher/mirrored-pause:3.6}"
export K3S_REQUIRE_PAUSE_IMAGE="${K3S_REQUIRE_PAUSE_IMAGE:-false}"
export K3S_BIN="${K3S_BIN:-/usr/bin/k3s}"
export K3S_PAUSE_TAR="${K3S_PAUSE_TAR:-/tmp/pause-image-arm64.tar}"
export K3S_IMAGE_TAR="${K3S_IMAGE_TAR:-/tmp/localhost_5000_mica-uniproton-app_xen-0.1.tar}"
export K3S_EDGE_NODE_NAME="${K3S_EDGE_NODE_NAME:-qemu-aarch64}"
export K3S_EDGE_NODE_IP="${K3S_EDGE_NODE_IP:-192.168.7.2}"
export K3S_CLOUD_SERVER_IMAGE="${K3S_CLOUD_SERVER_IMAGE:-rancher/k3s:v1.27.15-k3s1}"
export K3S_CLOUD_SERVER_CONTAINER="${K3S_CLOUD_SERVER_CONTAINER:-micrun-k3s-server}"
export K3S_CLOUD_SERVER_NAME="${K3S_CLOUD_SERVER_NAME:-cloud-srv}"
export K3S_CLOUD_SERVER_IP="${K3S_CLOUD_SERVER_IP:-192.168.7.10}"
export K3S_CLOUD_SERVER_SNAPSHOTTER="${K3S_CLOUD_SERVER_SNAPSHOTTER:-native}"
export K3S_CLOUD_SERVER_EXTRA_ARGS="${K3S_CLOUD_SERVER_EXTRA_ARGS:-}"
export K3S_CLOUD_KUBECTL_BIN="${K3S_CLOUD_KUBECTL_BIN:-k3s}"
export K3S_CLOUD_KUBECTL_SUBCOMMAND="${K3S_CLOUD_KUBECTL_SUBCOMMAND-kubectl}"
export K3S_CLOUD_NETWORK_NAME="${K3S_CLOUD_NETWORK_NAME:-micrun-cloud}"
export K3S_CLOUD_NETWORK_SUBNET="${K3S_CLOUD_NETWORK_SUBNET:-192.168.7.0/24}"
export K3S_CLOUD_NETWORK_GATEWAY="${K3S_CLOUD_NETWORK_GATEWAY:-192.168.7.1}"
export K3S_CLOUD_NETWORK_PARENT="${K3S_CLOUD_NETWORK_PARENT:-tap0}"
export K3S_TOKEN_PLAIN="${K3S_TOKEN_PLAIN:-micrun-dev-token}"
export K3S_LOCAL_ASSET_DIR="${K3S_LOCAL_ASSET_DIR:-/tmp/micrun-k3s-assets}"
export K3S_LOCAL_SERVER_BIN="${K3S_LOCAL_SERVER_BIN:-$K3S_LOCAL_ASSET_DIR/k3s-amd64}"
export K3S_LOCAL_KUBECTL_BIN="${K3S_LOCAL_KUBECTL_BIN:-$K3S_LOCAL_SERVER_BIN}"
export K3S_LOCAL_KUBECTL_SUBCOMMAND="${K3S_LOCAL_KUBECTL_SUBCOMMAND-kubectl}"
export K3S_LOCAL_KUBECONFIG="${K3S_LOCAL_KUBECONFIG:-}"
export K3S_LOCAL_SUDO_PASSWORD="${K3S_LOCAL_SUDO_PASSWORD:-}"
if [ "${K3S_KUBELET_ARGS+x}" = "x" ]; then
    export K3S_KUBELET_ARGS
fi
export K3S_LOCAL_SERVER_IP="${K3S_LOCAL_SERVER_IP:-10.0.2.2}"
export K3S_EDGE_USE_SYSTEM_CONTAINERD="${K3S_EDGE_USE_SYSTEM_CONTAINERD:-true}"
if [ "${K3S_EDGE_CONTAINERD_MODE+x}" != "x" ]; then
    if [ "$K3S_EDGE_USE_SYSTEM_CONTAINERD" = "true" ]; then
        export K3S_EDGE_CONTAINERD_MODE="external"
    else
        export K3S_EDGE_CONTAINERD_MODE="bundled"
    fi
fi
if [ "$K3S_EDGE_CONTAINERD_MODE" = "external" ]; then
    export K3S_CONTAINERD_ADDRESS="${K3S_CONTAINERD_ADDRESS:-/run/containerd/containerd.sock}"
    export K3S_EDGE_CTR_BIN="${K3S_EDGE_CTR_BIN:-ctr}"
    export K3S_EDGE_CTR_SUBCOMMAND="${K3S_EDGE_CTR_SUBCOMMAND-}"
else
    export K3S_CONTAINERD_ADDRESS="${K3S_CONTAINERD_ADDRESS:-/run/k3s/containerd/containerd.sock}"
    export K3S_EDGE_CTR_BIN="${K3S_EDGE_CTR_BIN:-$K3S_BIN}"
    export K3S_EDGE_CTR_SUBCOMMAND="${K3S_EDGE_CTR_SUBCOMMAND-ctr}"
fi
export K3S_LOCAL_USE_REVERSE_TUNNEL="${K3S_LOCAL_USE_REVERSE_TUNNEL:-false}"
export K3S_LOCAL_TUNNEL_REMOTE_PORT="${K3S_LOCAL_TUNNEL_REMOTE_PORT:-16443}"
export K3S_RUNTIME_CLASS_NAME="${K3S_RUNTIME_CLASS_NAME:-micrun}"
export K3S_NAMESPACE="${K3S_NAMESPACE:-default}"
export K3S_INTERACTION_MODE="${K3S_INTERACTION_MODE:-auto}"
export K3S_INTERACTION_POD_NAME="${K3S_INTERACTION_POD_NAME:-rtos-interaction}"
export K3S_INTERACTION_CONTAINER_NAME="${K3S_INTERACTION_CONTAINER_NAME:-rtos-app}"
export K3S_INTERACTION_EXPECT="${K3S_INTERACTION_EXPECT:-auto}"
export K3S_INTERACTION_KEEP_POD="${K3S_INTERACTION_KEEP_POD:-false}"
export K3S_INTERACTION_IMPORT_IMAGES="${K3S_INTERACTION_IMPORT_IMAGES:-true}"
export K3S_INTERACTION_NODE_SELECTOR="${K3S_INTERACTION_NODE_SELECTOR:-}"
export K3S_ATTACH_INPUT_DELAY="${K3S_ATTACH_INPUT_DELAY:-6}"
export K3S_ATTACH_LINE_DELAY="${K3S_ATTACH_LINE_DELAY:-3}"
export K3S_ATTACH_TAIL_DELAY="${K3S_ATTACH_TAIL_DELAY:-6}"
export K3S_ATTACH_TIMEOUT="${K3S_ATTACH_TIMEOUT:-60}"
export K3S_POD_WAIT_SECONDS="${K3S_POD_WAIT_SECONDS:-120}"
export K3S_POD_DELETE_TIMEOUT="${K3S_POD_DELETE_TIMEOUT:-60}"
export K3S_EDGE_TASK_WAIT_SECONDS="${K3S_EDGE_TASK_WAIT_SECONDS:-60}"
export K3S_EDGE_CLEANUP_WAIT_SECONDS="${K3S_EDGE_CLEANUP_WAIT_SECONDS:-60}"
export K3S_EDGE_CONTAINERD_ADDR="${K3S_EDGE_CONTAINERD_ADDR:-$K3S_CONTAINERD_ADDRESS}"
export K3S_EDGE_CONTAINERD_NS="${K3S_EDGE_CONTAINERD_NS:-k8s.io}"
export K3S_FORCE_DELETE_PODS="${K3S_FORCE_DELETE_PODS:-false}"

export TEST_TIMEOUT_DEFAULT="${TEST_TIMEOUT_DEFAULT:-60}"
export TEST_TIMEOUT_POD="${TEST_TIMEOUT_POD:-120}"
export TEST_TIMEOUT_CONTAINER="${TEST_TIMEOUT_CONTAINER:-30}"

export TEST_LOG_DIR="${TEST_LOG_DIR:-/tmp/micrun-tests}"
mkdir -p "$TEST_LOG_DIR"

export REMOTE_HOST="${REMOTE_HOST:-$TEST_REMOTE_HOST}"
export REMOTE_HOST="$TEST_REMOTE_HOST"

print_common_test_env() {
    echo "MicRun 测试环境:"
    echo "  REMOTE_HOST=$TEST_REMOTE_HOST"
    echo "  REMOTE_PORT=${TEST_REMOTE_PORT:-<default>}"
    echo "  REMOTE_PASSWORD=${TEST_REMOTE_PASSWORD:+<set>}"
    echo "  TEST_IMAGE=$TEST_IMAGE"
    echo "  K3S_SOURCE_IMAGE_REF=$K3S_SOURCE_IMAGE_REF"
    echo "  NERDCTL_NETWORK_MODE=$NERDCTL_NETWORK_MODE"
    echo "  IMAGE_PROFILE=$IMAGE_PROFILE"
    echo "  QEMU_IMAGE_TAR=${QEMU_IMAGE_TAR:-<auto-detect>}"
    echo "  QEMU_SOURCE_IMAGE_REF=$QEMU_SOURCE_IMAGE_REF"
    echo "  K3S_MASTER=$K3S_MASTER_NODE"
    echo "  K3S_WORKERS=$K3S_WORKER_NODES"
    echo "  K3S_KUBECTL_BIN=$K3S_KUBECTL_BIN"
    echo "  K3S_CTR_BIN=$K3S_CTR_BIN"
    echo "  K3S_SINGLE_NODE=$K3S_SINGLE_NODE"
    echo "  K3S_HOST_NETWORK=$K3S_HOST_NETWORK"
    echo "  K3S_TOLERATE_NOTREADY=$K3S_TOLERATE_NOTREADY"
    echo "  K3S_CONTAINER_COMMAND=$K3S_CONTAINER_COMMAND"
    echo "  K3S_PAUSE_IMAGE=$K3S_PAUSE_IMAGE"
    echo "  K3S_PAUSE_IMAGE_CANONICAL=$K3S_PAUSE_IMAGE_CANONICAL"
    echo "  K3S_EDGE_NODE=$K3S_EDGE_NODE_NAME@$K3S_EDGE_NODE_IP"
    echo "  K3S_CLOUD_SERVER=$K3S_CLOUD_SERVER_CONTAINER@$K3S_CLOUD_SERVER_IP"
    echo "  K3S_CLOUD_SERVER_SNAPSHOTTER=$K3S_CLOUD_SERVER_SNAPSHOTTER"
    echo "  K3S_CLOUD_SERVER_EXTRA_ARGS=${K3S_CLOUD_SERVER_EXTRA_ARGS:-<none>}"
    echo "  K3S_CLOUD_KUBECTL=${K3S_CLOUD_KUBECTL_BIN}${K3S_CLOUD_KUBECTL_SUBCOMMAND:+ $K3S_CLOUD_KUBECTL_SUBCOMMAND}"
    echo "  K3S_CLOUD_NETWORK=$K3S_CLOUD_NETWORK_NAME ($K3S_CLOUD_NETWORK_PARENT)"
    echo "  K3S_LOCAL_ASSET_DIR=$K3S_LOCAL_ASSET_DIR"
    echo "  K3S_LOCAL_SERVER_BIN=$K3S_LOCAL_SERVER_BIN"
    echo "  K3S_LOCAL_KUBECTL_BIN=$K3S_LOCAL_KUBECTL_BIN"
    echo "  K3S_LOCAL_KUBECONFIG=${K3S_LOCAL_KUBECONFIG:-<unset>}"
    echo "  K3S_KUBELET_ARGS=${K3S_KUBELET_ARGS:-<none>}"
    echo "  K3S_LOCAL_SERVER_IP=$K3S_LOCAL_SERVER_IP"
    echo "  K3S_EDGE_USE_SYSTEM_CONTAINERD=$K3S_EDGE_USE_SYSTEM_CONTAINERD"
    echo "  K3S_EDGE_CONTAINERD_MODE=$K3S_EDGE_CONTAINERD_MODE"
    echo "  K3S_EDGE_CONTAINERD_ADDR=$K3S_EDGE_CONTAINERD_ADDR"
    echo "  K3S_LOCAL_USE_REVERSE_TUNNEL=$K3S_LOCAL_USE_REVERSE_TUNNEL"
    echo "  K3S_INTERACTION_MODE=$K3S_INTERACTION_MODE"
    echo "  K3S_INTERACTION_POD=$K3S_NAMESPACE/$K3S_INTERACTION_POD_NAME"
    echo "  K3S_INTERACTION_EXPECT=$K3S_INTERACTION_EXPECT"
    echo "  LOG_DIR=$TEST_LOG_DIR"
    echo ""
}

print_io_test_env() {
    echo "MicRun IO Test Environment:"
    echo "  REMOTE_HOST=$TEST_REMOTE_HOST"
    echo "  REMOTE_PORT=${TEST_REMOTE_PORT:-<default>}"
    echo "  REMOTE_PASSWORD=${TEST_REMOTE_PASSWORD:+<set>}"
    echo "  TEST_IMAGE=$TEST_IMAGE"
    echo "  NERDCTL_NETWORK_MODE=$NERDCTL_NETWORK_MODE"
    echo "  IMAGE_PROFILE=$IMAGE_PROFILE"
    echo "  QEMU_IMAGE_TAR=${QEMU_IMAGE_TAR:-<auto-detect>}"
    echo "  QEMU_SOURCE_IMAGE_REF=$QEMU_SOURCE_IMAGE_REF"
}
