#!/bin/bash
# For starting, stopping and restarting UniProton
# Note:
#   only supports single-core.
#   Please use 'maxcpus=' to reserve one cpu for UniProton.
#   Please use 'memmap=' to reserve mem region for UniProton.
set -e

FIRMWARE_PATH="/lib/firmware"
CPU_SYSTEM="/sys/devices/system/cpu"
CLIENT_OS=""
TARGET_CPU=""

IGB_DRV_PATH="/sys/bus/pci/drivers/igb"
I210_DRV_PATH="/sys/bus/pci/drivers/i210_eth"

declare -i ETH_ID_UNBIND
ETH_ID_UNBIND=-1

ETHERNET_NAME=""

# Note: Please set 'memmap=512M\$0x110000000'
RESERVED_MEM_BASE=0x110000000
RESERVED_MEM_SIZE=0x20000000
# Note:
# TEXT_ADDR needs to be larger than:
#   RESERVED_MEM_BASE + BAR_TABLE_SIZE(0x100000)
#    + DMA_TABLE_SIZE(0x200000) + SHAREMEM_TABLE_SIZE(0x2000000)
#    + LOG_TABLE(0x200000)
TEXT_ADDR=0x118000000
DEBUG=""

usage()
{
	cat <<-END >&2
	Usage: $0 { COMMAND | --help }

	  Available commands:
	    start { CLIENT } [ -d | --debug ] [ -x | --ethx <id>]
	          CLIENT            # Specify the client OS to be loaded
	          -d --debug        # Start the gdb and debug the client OS.
	          -x --ethx <id>    # Use the <id> i210 ethernet adapter for rtos
	                              default value(-1): the last ethernet adapter
	    stop                    # Stop the client OS

	  eg,
	    # deploy the UniProton
	        $0 start uniproton.bin

	    # stop the UniProton
	        $0 stop

	    # Use gdb to debug the UniProton
	        $0 start uniproton.bin --debug
	END
	exit
}

die() {
	echo >&2 "$@"
	echo 1 > "${CPU_SYSTEM}/cpu${TARGET_CPU}/online"
	echo 0 > "${CPU_SYSTEM}/cpu${TARGET_CPU}/online"
	exit 1
}

eth_unbind_igb()
{
	if [ ! -d ${IGB_DRV_PATH} ]; then
		return
	fi
	# 获取igb驱动绑定的网卡个数
	pushd "${IGB_DRV_PATH}"

	declare -i eth_cnt
	eth_cnt=0
	for entry in `ls ./`; do
		if [[ "$entry" == *:*:*.* ]]; then
			eth_cnt=eth_cnt+1
		fi
	done

	if [[ eth_cnt == 0 ]]; then
		popd
		die "failed to find the network adapter device. Uninstalled?"
	fi

	# 确定要解绑第几个网卡 -1 表示最后一个
	declare -i eth_id_unbind
	eth_id_unbind=(ETH_ID_UNBIND+eth_cnt)%eth_cnt
	eth_cnt=0
	for entry in `ls ./`; do
		if [[ "$entry" == *:*:*.* ]]; then
			if [[ $eth_cnt == $eth_id_unbind ]]; then
				echo $entry > unbind
				ETHERNET_NAME=$entry  # 记录网卡的bdf号，用于i210_eth进行绑定
				echo "igb unbind $entry"
			fi
			eth_cnt=eth_cnt+1
		fi
	done

	popd
}

eth_unbind_i210()
{
	if [ ! -d ${I210_DRV_PATH} ]; then
		return
	fi

	pushd "${I210_DRV_PATH}"
	for entry in `ls ./`; do
		if [[ "$entry" == *:*:*.* ]]; then
			echo $entry > unbind
			ETHERNET_NAME=$entry  # 记录网卡的bdf号，用于igb进行恢复绑定
			echo "eth_i210 unbind $entry"
			break;
		fi
	done
	popd
	rmmod eth_i210
}

eth_bind_igb()
{
	if [ ! -d ${IGB_DRV_PATH} ]; then
		return
	fi

	pushd "${IGB_DRV_PATH}"
	if [[ ${ETHERNET_NAME} ]]; then
		echo ${ETHERNET_NAME} > bind
		echo "igb bind ${ETHERNET_NAME}"
	fi
	popd
}

eth_bind_i210()
{
	if [ ! -d ${I210_DRV_PATH} ]; then
		return
	fi

	pushd "${I210_DRV_PATH}"
	if [[ ${ETHERNET_NAME} ]]; then
		echo ${ETHERNET_NAME} > bind
		echo "i210 bind ${ETHERNET_NAME}"
	fi
	popd
}

check_status()
{
	sleep 1
	local pid=$(pidof mica_main)
	if kill -0 ${pid}; then
		echo "UniProton start success!"
	else
		die "UniProton start failed! Aborting."
	fi
}

do_start()
{
	## 如果之前有网卡的配置，这里先恢复
	eth_unbind_i210
	eth_bind_igb

	if [ ! -f "$(modinfo -F filename mcs_km 2>/dev/null)" ]; then
		die "Module mcs_km.ko not found in directory /lib/modules. Aborting."
	fi
	modprobe mcs_km rmem_base=${RESERVED_MEM_BASE} rmem_size=${RESERVED_MEM_SIZE}
	if [ $? != 0 ]; then
		die "Request mem failed, did you reserve the memory with 'memmap='? Aborting."
	fi

	if [ ! -f "$(modinfo -F filename eth_i210 2>/dev/null)" ]; then
		die "Module eth_i210.ko not found in directory /lib/modules. Aborting."
	fi
	modprobe eth_i210 load_addr=${TEXT_ADDR}
	if [ $? != 0 ]; then
		die "eth i210 init failed, did you reserve ethnet device (intel i210) Aborting."
	fi

	## 网卡解绑定 原生驱动igb
	eth_unbind_igb

	## 网卡绑定 自研驱动eth_i210
	eth_bind_i210

	# step1: stop the target cpu
	echo 0 > "${CPU_SYSTEM}/cpu${TARGET_CPU}/online"

	# step2: run mica to start client OS
	if [ -n "${DEBUG}" ]; then
		mica_main -b ${FIRMWARE_PATH}/ap_boot \
	  -c ${TARGET_CPU} \
	  -t ${CLIENT_OS} -a ${TEXT_ADDR} \
	  ${DEBUG}
	else
		mica_main -b ${FIRMWARE_PATH}/ap_boot \
	  -c ${TARGET_CPU} \
	  -t ${CLIENT_OS} -a ${TEXT_ADDR} &
	  check_status
	fi
}

do_stop()
{
	local pid=$(pidof mica_main)
	if [ -z "${pid}" ]; then
		die "mica is not running. No need to stop the UniProton."
	fi

	local target=$(ps -o cmd= -p ${pid} | awk -F '-c ' '{print $2}' | awk '{print $1}')
	echo "Stopping CPU${target}"
	# step1: kill mica
	kill -SIGINT ${pid} >/dev/null 2>&1

	# step2: restart the target cpu
	echo 1 > "${CPU_SYSTEM}/cpu${target}/online"
	if [ $? != 0 ]; then
		die "UniProton stop failed! Aborting."
	else
		echo "UniProton stopped."
	fi

	## 如果之前有网卡的配置，这里先恢复
	eth_unbind_i210
	eth_bind_igb
}

get_free_cpu()
{
	# use the last free cpu
	TARGET_CPU="$(cat ${CPU_SYSTEM}/offline | awk -F '-' '{print $NF}')"

	# If there are no free cpu, select the last online cpu.
	if [ -z "${TARGET_CPU}" ]; then
		TARGET_CPU="$(cat ${CPU_SYSTEM}/online | awk -F '-' '{print $NF}')"
		if [ -z "${TARGET_CPU}" ]; then
			die "No CPU available for UniProton. Aborting."
		fi
	fi
}

check_opt()
{
	ARGS=`getopt -o hdx: --long help,debug,ethx: -n "$0" -- "$@"`
	if [ $? != 0 ]; then
		usage
	fi

	eval set -- "${ARGS}"

	while true
	do
		case "$1" in
			-h|--help)
				usage
				;;
			-d|--debug)
				DEBUG=" -d "
				shift
				;;
			-x|--ethx)
				ETH_ID_UNBIND=`expr $2+0`
				shift 2
				;;
			--)
				shift
				break
				;;
			*)
				break
				;;
		esac
	done

	# check client OS
	CLIENT_OS=$(basename $@ 2>/dev/null)
	if [ ! -f "${CLIENT_OS}" ]; then
		die "Not found client OS: ${CLIENT_OS}. Aborting."
	fi
}

case "$1" in
	start)
		shift
		check_opt $@
		get_free_cpu
		echo "Starting ${CLIENT_OS} on CPU${TARGET_CPU}"
		do_start
		;;
	stop)
		shift
		do_stop
		;;
	*)
		usage
esac

exit 0
